### ISSUE TITLE
Aggregate Swiss tournament results

### ISSUE THREAD

**Issue by eduherminio** [eduherminio/LichessTournamentAggregator#15]
Depends on Lichess making them available via their API (https://github.com/lichess-org/api/issues/35).

**Comment by jonium** [comment]
any news?

**Comment by eduherminio** [comment]
I'll try to put something together in the next few days.
Out of curiosity, how often do you use the tool?

**Comment by jonium** [comment]
I’m not using your tool at the moment because it doesn’t support swiss tournaments, I weekly process them manually

 

Cordiali saluti

Pier Paolo Ronzino

Ormag

 

Tel./ph. (+39) 0833 281213 

via Hydruntum, 1 - 73011, Alezio (LE)

 <http://www.ormag.com> www.ormag.com 

E-mail  ***@***.***

 

Da: Eduardo Cáceres ***@***.*** 
Inviato: giovedì 15 aprile 2021 03:45
A: eduherminio/LichessTournamentAggregator ***@***.***>
Cc: jonium ***@***.***>; Comment ***@***.***>
Oggetto: Re: [eduherminio/LichessTournamentAggregator] Aggregate Swiss tournament results (#15)

 

I'll try to put something together in the next few days.
Out of curiosity, how often do you use the tool?

**Comment by eduherminio** [comment]
Release [0.3.0](https://github.com/eduherminio/LichessTournamentAggregator/releases/tag/v0.3.0) adds basic support for swiss tournaments, as long as the whole tournament url is specified (and only the id).
Feel free to raise any issues/questions.

**Comment by jonium** [comment]
Hello eduherminio,
I used the tool and it worked great until last week.
Now there seems to be a problem with scores, maybe some change in the trf files.

Best regards
jonium

**Comment by eduherminio** [comment]
@jonium Could you try to help me reproducing it by opening a new issue with:
* Application version and Operative System you're using.
* Exact command and input you're having issues with.

**Comment by jonium** [comment]
Windows 10
LichessTournamentAggregator.0.3.0-win-x86.exe

 `Type or paste the Lichess tournament ids or full tournament urls that you want to aggregate, separated by a new line.
Hit enter again when finished.
https://lichess.org/swiss/v0Vzcbnz
https://lichess.org/swiss/IEreYkx7
https://lichess.org/swiss/wfrOO3Du

Aggregating tournaments:
*       https://lichess.org/swiss/v0Vzcbnz
*       https://lichess.org/swiss/IEreYkx7
*       https://lichess.org/swiss/wfrOO3Du

Aggregation finished, results can be found in C:\Users\xxx\Results_2021-05-18__13_43_02.csv

Press intro to close this window`

here the result:
`





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:\Users\JONIUM~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel="File-List" href="file:///C:\Users\JONIUM~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>





# | Username | Total Score | Total tie breaks | Average Performance | Max Rating | Title | Ranks | Scores | Tie breaks
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | Protoscacchista | 0 | 74.5 | 2053.67 | 2055 | &nbsp; | [7, 12, 4] | [0, 0, 0] | [23.75, 18, 32.75]
2 | emadam | 0 | 64.25 | 2053 | 1888 | &nbsp; | [8, 10, 8] | [0, 0, 0] | [20.75, 19.5, 24]
3 | polistirolo99 | 0 | 59.25 | 1917.67 | 2057 | &nbsp; | [6, 8, 18] | [0, 0, 0] | [24.25, 20.5, 14.5]
4 | maurodik | 0 | 57.5 | 1980.33 | 2060 | &nbsp; | [3, 30, 6] | [0, 0, 0] | [26.5, 10.5, 20.5]
5 | luigiciavarra | 0 | 57 | 2223.5 | 2080 | &nbsp; | [4, 3] | [0, 0] | [23.75, 33.25]
6 | Altapinus | 0 | 55.75 | 2197.33 | 2065 | &nbsp; | [5, 5, 38] | [0, 0, 0] | [24.5, 26.25, 5]
7 | IlFaraoneDelleSabbie | 0 | 51.75 | 1772.67 | 2111 | &nbsp; | [4, 61, 5] | [0, 0, 0] | [27.5, 0, 24.25]
8 | neronespartacus94 | 0 | 49.5 | 2209 | 2343 | &nbsp; | [2, 17] | [0, 0] | [33.5, 16]
9 | vladyspel | 0 | 48.5 | 1902 | 1929 | &nbsp; | [9, 17, 9] | [0, 0, 0] | [15.25, 12.75, 20.5]
10 | Check71 | 0 | 47.25 | 1847.67 | 2065 | &nbsp; | [12, 9, 33] | [0, 0, 0] | [21.25, 20, 6]
11 | ErMejo63 | 0 | 44.5 | 1759 | 1808 | &nbsp; | [10, 25, 11] | [0, 0, 0] | [15, 13.5, 16]
12 | Gregory4 | 0 | 42.75 | 1923.33 | 1905 | &nbsp; | [33, 14, 10] | [0, 0, 0] | [9.75, 15, 18]
13 | Borderina2021 | 0 | 40.5 | 2342 | 1989 | &nbsp; | [2] | [0] | [40.5]
14 | fmex | 0 | 36.5 | 1667.33 | 1690 | &nbsp; | [22, 26, 20] | [0, 0, 0] | [13, 12, 11.5]
15 | Silviman | 0 | 34 | 1625 | 1582 | &nbsp; | [26, 29, 12] | [0, 0, 0] | [10.25, 12.75, 11]
16 | pelpison | 0 | 33 | 1867.5 | 1990 | &nbsp; | [13, 13] | [0, 0] | [16, 17]
17 | endy_91 | 0 | 32.5 | 2326 | 2174 | &nbsp; | [3] | [0] | [32.5]
18 | gb60 | 0 | 32.25 | 1868.5 | 1932 | &nbsp; | [24, 13] | [0, 0] | [14, 18.25]
19 | danydomy | 0 | 31.75 | 1755 | 1795 | &nbsp; | [23, 34, 7] | [0, 0, 0] | [11.5, 4, 16.25]
20 | jonium | 0 | 31.75 | 1732 | 1658 | &nbsp; | [25, 18, 23] | [0, 0, 0] | [11, 11.75, 9]
21 | Damianlamy | 0 | 31.5 | 2386 | 2259 | &nbsp; | [2] | [0] | [31.5]
22 | tarsis | 0 | 30.75 | 2083.5 | 2115 | &nbsp; | [23, 16] | [0, 0] | [16.75, 14]
23 | adesso | 0 | 30 | 1632.67 | 1709 | &nbsp; | [27, 19, 24] | [0, 0, 0] | [10.25, 11.25, 8.5]
24 | Tornosubito | 0 | 29.5 | 1845 | 1905 | &nbsp; | [15, 15] | [0, 0] | [13.75, 15.75]
25 | paolocova | 0 | 27.75 | 1603.67 | 1715 | &nbsp; | [24, 35, 25] | [0, 0, 0] | [11.25, 8.5, 8]
26 | Hawkeye88 | 0 | 27 | 1492.67 | 1708 | &nbsp; | [20, 57, 19] | [0, 0, 0] | [14.5, 0, 12.5]
27 | mfischer | 0 | 25 | 1757 | 2001 | &nbsp; | [21, 20] | [0, 0] | [14, 11]
28 | oiacob | 0 | 23.75 | 1634 | 1631 | &nbsp; | [15, 26] | [0, 0] | [13.75, 10]
29 | mikichess6 | 0 | 22.25 | 2193 | 2076 | &nbsp; | [7] | [0] | [22.25]
30 | pepi81it | 0 | 21 | 1607 | 2055 | &nbsp; | [6, 49] | [0, 0] | [21, 0]
31 | Sergejs | 0 | 20.5 | 2453 | 2424 | FM | [22] | [0] | [20.5]
32 | NiHiLo | 0 | 20.25 | 1779.5 | 1941 | &nbsp; | [29, 22] | [0, 0] | [10.75, 9.5]
33 | Sgrazz | 0 | 18.25 | 1587.5 | 1651 | &nbsp; | [35, 28] | [0, 0] | [9.5, 8.75]
34 | sengiofficial | 0 | 18 | 2197 | 2115 | &nbsp; | [11] | [0] | [18]
35 | Ziogino | 0 | 18 | 1339 | 1205 | &nbsp; | [30, 39, 34] | [0, 0, 0] | [10.5, 3.5, 4]
36 | Presente1994 | 0 | 17.75 | 1846 | 2089 | &nbsp; | [14] | [0] | [17.75]
37 | Giacomolagaetana | 0 | 17.75 | 1351 | 1469 | &nbsp; | [38, 32, 37] | [0, 0, 0] | [6.75, 7.5, 3.5]
38 | Marcel1969 | 0 | 17.5 | 1710.5 | 1444 | &nbsp; | [11, 38] | [0, 0] | [13.5, 4]
39 | grouchom2 | 0 | 17 | 1516.33 | 1316 | &nbsp; | [32, 48, 32] | [0, 0, 0] | [8.5, 1, 7.5]
40 | Nikhofrik | 0 | 17 | 1344.33 | 1279 | &nbsp; | [36, 36, 43] | [0, 0, 0] | [8.5, 8.5, 0]
41 | Sempreavanti61 | 0 | 16.25 | 1222.33 | 1216 | &nbsp; | [47, 43, 31] | [0, 0, 0] | [5.5, 2.75, 8]
42 | Giac-jack | 0 | 15.5 | 1778 | 1409 | &nbsp; | [19] | [0] | [15.5]
43 | krobbi | 0 | 14.75 | 1729 | 1786 | &nbsp; | [28] | [0] | [14.75]
44 | Pom_a_million_Isotta | 0 | 14.5 | 1808 | 2131 | &nbsp; | [14] | [0] | [14.5]
45 | Intrinseco | 0 | 14.5 | 1342 | 1300 | &nbsp; | [37, 30] | [0, 0] | [5, 9.5]
46 | cavaliereyedi | 0 | 14 | 1242 | 1767 | &nbsp; | [49, 62, 21] | [0, 0, 0] | [3, 0, 11]
47 | maxgambit61 | 0 | 13.5 | 1985 | 1903 | &nbsp; | [16] | [0] | [13.5]
48 | Francesco13 | 0 | 13.5 | 1862 | 1822 | &nbsp; | [16] | [0] | [13.5]
49 | CasalPalocco | 0 | 13.5 | 1481 | 1658 | &nbsp; | [17] | [0] | [13.5]
50 | Dillomer | 0 | 13.5 | 1335.33 | 1188 | &nbsp; | [45, 41, 27] | [0, 0, 0] | [0, 4.5, 9]
51 | CarmineBartolomeo | 0 | 11.75 | 1338 | 1448 | &nbsp; | [43, 40] | [0, 0] | [6.75, 5]
52 | TerzoTempo | 0 | 10 | 1751 | 1476 | &nbsp; | [18] | [0] | [10]
53 | spuledda | 0 | 10 | 1477 | 1334 | &nbsp; | [31] | [0] | [10]
54 | rosignoli | 0 | 9.75 | 1465 | 1427 | &nbsp; | [34] | [0] | [9.75]
55 | BarryKripke | 0 | 9.5 | 1767 | 2006 | &nbsp; | [21] | [0] | [9.5]
56 | gaetanomonticelli | 0 | 9.25 | 1455.5 | 1651 | &nbsp; | [39, 41] | [0, 0] | [6.25, 3]
57 | Tentagleman | 0 | 9 | 1638 | 1574 | &nbsp; | [27] | [0] | [9]
58 | inviluca | 0 | 8.75 | 1594 | 1487 | &nbsp; | [31] | [0] | [8.75]
59 | MicheleRuffo | 0 | 8.5 | 1585 | 1526 | &nbsp; | [28] | [0] | [8.5]
60 | Backthunder | 0 | 8.5 | 1235 | 1252 | &nbsp; | [46, 46] | [0, 0] | [4.5, 4]
61 | jazztrain | 0 | 7 | 1234.67 | 1723 | &nbsp; | [37, 63, 45] | [0, 0, 0] | [7, 0, 0]
62 | Gem0508 | 0 | 7 | 1229.5 | 1295 | &nbsp; | [51, 36] | [0, 0] | [2.5, 4.5]
63 | caccascio | 0 | 6 | 1508 | 1484 | &nbsp; | [33] | [0] | [6]
64 | Morfe0 | 0 | 6 | 1253.5 | 1082 | &nbsp; | [40, 58] | [0, 0] | [6, 0]
65 | Cadio84 | 0 | 5.75 | 1452.5 | 1542 | &nbsp; | [41, 47] | [0, 0] | [5.75, 0]
66 | Margi71 | 0 | 5.25 | 1136 | 1032 | &nbsp; | [42, 44] | [0, 0] | [2.75, 2.5]
67 | Paolicchia1412 | 0 | 4.5 | 1476 | 1830 | &nbsp; | [29] | [0] | [4.5]
68 | Capi48 | 0 | 4 | 2228 | 2240 | &nbsp; | [42] | [0] | [4]
69 | Solaar21 | 0 | 4 | 1595 | 1956 | &nbsp; | [45] | [0] | [4]
70 | Belistumegare | 0 | 4 | 1195 | 1031 | &nbsp; | [35] | [0] | [4]
71 | Pinco___Pallino | 0 | 3 | 1479 | 1741 | &nbsp; | [42] | [0] | [3]
72 | deriddoo | 0 | 3 | 1459 | 1652 | &nbsp; | [48] | [0] | [3]
73 | Pepeperepe | 0 | 2.5 | 1240 | 1374 | &nbsp; | [44] | [0] | [2.5]
74 | check83 | 0 | 2 | 1582 | 1412 | &nbsp; | [47] | [0] | [2]
75 | gigino2020 | 0 | 2 | 1389 | 1540 | &nbsp; | [52, 48] | [0, 0] | [2, 0]
76 | giorgioV1989 | 0 | 2 | 1315 | 1356 | &nbsp; | [53, 39] | [0, 0] | [1, 1]
77 | LaZzA10 | 0 | 1.25 | 1477 | 1570 | &nbsp; | [49, 46] | [0, 0] | [1.25, 0]
78 | Fix65 | 0 | 1 | 1063 | 926 | &nbsp; | [40] | [0] | [1]
79 | lasalle2o | 0 | 0.5 | 1497.5 | 1339 | &nbsp; | [54, 50] | [0, 0] | [0, 0.5]
80 | GianC92 | 0 | 0.5 | 1243 | 1380 | &nbsp; | [54] | [0] | [0.5]
81 | daniele1945 | 0 | 0 | 1528 | 1479 | &nbsp; | [53] | [0] | [0]
82 | gattofilippo | 0 | 0 | 1490 | 1323 | &nbsp; | [60] | [0] | [0]
83 | MaestroFelice69 | 0 | 0 | 1087 | 1161 | &nbsp; | [55] | [0] | [0]
84 | Francescobernardi | 0 | 0 | 1083 | 882 | &nbsp; | [50] | [0] | [0]
85 | StrategaMeticoloso | 0 | 0 | 1007 | 717 | &nbsp; | [44] | [0] | [0]
86 | Pometti1975 | 0 | 0 | 967.5 | 933 | &nbsp; | [50, 59] | [0, 0] | [0, 0]
87 | CDSPARCHEGGIO | 0 | 0 | 943 | 1147 | &nbsp; | [55] | [0] | [0]
88 | Ramirez11 | 0 | 0 | 856 | 1932 | &nbsp; | [51] | [0] | [0]
89 | FILIPP0-AV | 0 | 0 | 0 | 1810 | &nbsp; | [51] | [0] | [0]
90 | Giannipp | 0 | 0 | 0 | 1590 | &nbsp; | [52] | [0] | [0]
91 | nuncar | 0 | 0 | 0 | 2101 | &nbsp; | [56] | [0] | [0]






`
