### ISSUE TITLE
Ranks column error

### ISSUE THREAD

**Issue by jonium** [eduherminio/LichessTournamentAggregator#26]
Hello eduherminio,
I notice that in the column Ranks the values are calculeted +1, e.g. the winner has 2, the second has 3 and so on...

**Comment by eduherminio** [comment]
This should be fixed in [v0.3.2](https://github.com/eduherminio/LichessTournamentAggregator/releases/tag/v0.3.2).
Thanks for using LichessTournamentAggregator!
